app:
  env: "dev"
  port: 8080
  debug: true
  log_level: "debug"

db:
  host: "127.0.0.1"
  user: 
  password: 
  port: 5432
  dbname: "mydb"
  sslmode: "disable"

secure:
  cors_allow_origins: ""
  jwt:
    private_key_base64: ""
    public_key_base64: ""
    access_expiration_min: 60
    refresh_expiration_day: 30
    cookie:
      secure: false
      http_only: true
      same_site: "Lax"
      domain: "localhost"